version: '3.6'
services:
  nginx:
    build: infrastructure/nginx
    container_name: test_nginx
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/configuration/default.conf:/etc/nginx/conf.d/default.conf

  fpm:
    build: infrastructure/fpm
    container_name: test_fpm
    ports:
      - "2222:22"
    volumes:
      - .:/app
    working_dir: /app

  mysql:
    image: mysql:5.7
    container_name: test_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
